### ISSUE TITLE
payload isnot working 

### ISSUE THREAD

**Issue by 0xIslamTaha** [EgeBalci/HERCULES#2]
I created a payload as the following image
![screenshot from 2016-06-08 12-17-51](https://cloud.githubusercontent.com/assets/17981089/15891089/9db509a4-2d7b-11e6-8e28-12d7508c320c.png)

Then I began the nc -l mood
![screenshot from 2016-06-08 12-18-03](https://cloud.githubusercontent.com/assets/17981089/15891095/abcaca56-2d7b-11e6-8f7f-14c0cdeed5e4.png)

Then I execute the payload.exe on X86 windows 7
![screenshot from 2016-06-08 12-18-30](https://cloud.githubusercontent.com/assets/17981089/15891107/bbe2928e-2d7b-11e6-8da9-0edf8d3fc437.png)

The result is:
![screenshot from 2016-06-08 12-18-14](https://cloud.githubusercontent.com/assets/17981089/15891115/c2d08114-2d7b-11e6-9d21-68c4bfa63530.png)

And I didnt receive any thing on port 4444

**Comment by EgeBalci** [comment]
I just tested the payload an it worked for me on WIN 7 machine, issue could be related with your virtual machine try it on another machine and try to run HERCULES code from souce with `go run HERCULES.go`
![screenshot from 2016-06-08 13-38-24](https://cloud.githubusercontent.com/assets/17179401/15891745/ba115fd2-2d7e-11e6-92d9-b7a9ddf43065.png)

**Comment by 0xIslamTaha** [comment]
I did it twice with a differant machine and I reinstall the go lang with the latest version 1.6.2. While I'm building the payload these message appears
![screenshot from 2016-06-08 15-24-18](https://cloud.githubusercontent.com/assets/17981089/15895932/6c90d892-2d96-11e6-8077-538345327fbd.png)
![screenshot from 2016-06-08 15-24-25](https://cloud.githubusercontent.com/assets/17981089/15895931/6c902aaa-2d96-11e6-8088-84b6e228a165.png)

After I create it, I still have the same error in a two different version machine! 

any suggestions?
Thnaks

**Comment by EgeBalci** [comment]
It seems like a very rare case, honestly i have no idea what is wrong :/ 

Try to change processor core numbers on virtual machine if this not helps send me a payload sample for understanding the source of the problem.
![screenshot from 2016-06-08 17-37-44](https://cloud.githubusercontent.com/assets/17179401/15898557/78ab5b6a-2da1-11e6-9bd9-cc2a992db749.png)

**Comment by 0xIslamTaha** [comment]
I found that this function CheckGolang() compare the current go version with 1.6.1 and if not, It will pop-up this message, So I think u have to edit this part to check 1.6.2 instead of 1.6.1.

I wanna know if your VM is 64-bit or 32-bit cos mine is 32-bit.

I tried to edit the payload.go it self but i faced a syntex error in it, so please have a look in it 

[HerC_payload_edit.go.zip](https://github.com/EgeBalci/HERCULES/files/305113/HerC_payload_edit.go.zip)

**Comment by EgeBalci** [comment]
Yes CheckGolang() function needs to be fixed i will deal whit it as soon as possible but it is not the problem that causes your error.
I have checked the code several times in different platforms but i didn't find any error like yours, unfortunately i can't help you but if you find a reason or solution about it please let me know.

**Comment by islamTaha12** [comment]
Thanks for your help. 
May I know what is your VM windows 7 version?

**Comment by 0xIslamTaha** [comment]
@EgeBalci I finally found that the payload is working well in x64 but its not working in x86. Please, check this issue.  Also, The ~Meterperter module attract the antivirus ... Have you any suggestions to bypass that?

**Comment by EgeBalci** [comment]
Good news !
I finally figured out whats is wrong with my code and fixed it, now you can run x86 payloads with no error.

**Comment by 0xIslamTaha** [comment]
Good work I will test it.
I would like to knw if there is another method to load the meterpretre payload without create .bat file in the hard desk? I mean we can load it in a memory and exedute it without touch the hard disk to not attract tbe AV?

**Comment by EgeBalci** [comment]
Yes i will implement more methods for executing meterpreter in future versions including memory byte injections and dll preloading atacks.
