### ISSUE TITLE
no-ip  ADRESS IN HOST Problem!

### ISSUE THREAD

**Issue by ghost** [EgeBalci/HERCULES#6]
you just did an awsome work here but we can't use a DNS adress in Host like no-ip!!! and tha's a bit of problem

**Comment by EgeBalci** [comment]
Yes unfotunatley HERCULES don't have DNS address support. But no-ip and all other dynamic dns providers  also gives you a numeric ip address to work with ;D

**Comment by ghost** [comment]
yes i know ,but numeric ip address is always changing i,and i can't
establish persistence without usong no-ip in host!!

2016-07-05 19:32 GMT+01:00 Ege Balcı notifications@github.com:
