### ISSUE TITLE
[!] ERROR : golang is not installed

### ISSUE THREAD

**Issue by IceTeaGod** [EgeBalci/HERCULES#9]
I want to try this new script but when I install it I get this : 
![issue](https://cloud.githubusercontent.com/assets/22253296/19019094/177a8834-8882-11e6-82fd-216295999b9a.png)
![issue](https://cloud.githubusercontent.com/assets/22253296/19019097/1d1b8d2e-8882-11e6-9485-e39546318597.png)
Any Fix? Thank you! :)

**Comment by EgeBalci** [comment]
This is possibly because of the changes of golang installation path, try manualy cloning the https://github.com/EgeBalci/EGESPLOIT.git library to your /usr/lib/go-1.6/src/ path
